-- The ledger itself.
--
-- ## One signed amount, not a debit column and a credit column
--
-- Every accounting textbook draws two columns, and the Trial Balance screen
-- will draw two columns. The TABLE stores one signed integer, debit positive,
-- because the property that has to be enforced is "these lines sum to zero"
-- and with two columns that is sum(debit) = sum(credit) plus a second rule
-- that no row may fill both. One column makes the first trivial and the second
-- impossible to violate. The two columns are a projection:
--
--   debit  = greatest(amount_cents, 0)
--   credit = greatest(-amount_cents, 0)
--
-- Debit positive rather than credit positive so an account's balance is
-- sum(amount_cents) and reads the way its type expects: assets and expenses
-- carry debit balances, so they come out positive.
--
-- ## Why the balance check is a DEFERRED constraint trigger
--
-- It cannot be a CHECK -- a CHECK sees one row and the property is about a set.
-- It cannot be a plain AFTER trigger either, because the first line of a
-- two-line entry is always unbalanced; a non-deferred trigger would refuse
-- every entry ever written. Deferring to commit is what makes the intermediate
-- state legal and the final state judged.
--
-- Putting it here rather than only inside post_journal_entry() is the point.
-- The RPC checks too, because a clear error beats a constraint violation. But
-- the RPC is code and code has bugs, and "the books balance" is the one
-- property that must survive a bug in the thing that writes them.

create table public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops(id) on delete cascade,
  period_id uuid not null references public.accounting_periods(id),
  -- The date the entry BELONGS to, which is not created_at. A bill entered on
  -- 3 September for August utilities is dated in August; that is what accrual
  -- means and what the period gate is measured against.
  entry_date date not null,
  -- Human-facing, unique per shop, generated by post_journal_entry. Null while
  -- a draft, because a reference nobody can see yet is a number burned for
  -- nothing.
  reference text,
  description text not null check (length(trim(description)) > 0),
  -- Which door wrote it. Only 'manual' and 'opening' are reachable in this
  -- phase; the rest are listed now so the posting phases add no enum values to
  -- a table that by then has rows.
  source text not null default 'manual' check (source in (
    'manual','sale','refund','settlement','bill','payment','payroll',
    'stock','count','transfer','asset','depreciation','close','opening'
  )),
  status text not null default 'draft' check (status in ('draft','posted','reversed')),
  -- Optional dimension. A shop with one store leaves it null; a shop with three
  -- gets a P&L per branch without a second set of accounts.
  location_id uuid references public.shop_locations(id),
  -- Set on the ORIGINAL when it is reversed, and on the reversal pointing back.
  -- Both directions, so neither entry can be read without finding the other.
  reverses_entry_id uuid references public.journal_entries(id),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (shop_id, reference)
);
create index journal_entries_shop_date_idx on public.journal_entries(shop_id, entry_date desc, created_at desc);
create index journal_entries_period_idx on public.journal_entries(period_id);

create table public.journal_lines (
  id uuid primary key default gen_random_uuid(),
  entry_id uuid not null references public.journal_entries(id) on delete cascade,
  -- No ON DELETE: an account that has been posted to must not be deletable, and
  -- the reference is what enforces it. Archiving is the supported way out.
  account_id uuid not null references public.accounts(id),
  -- Debit positive, credit negative. Never zero -- a zero line records nothing
  -- and two of them would sum to zero and pass the balance check.
  amount_cents bigint not null check (amount_cents <> 0),
  location_id uuid references public.shop_locations(id),
  memo text
);
create index journal_lines_entry_idx on public.journal_lines(entry_id);
-- Every report groups by account and filters by date, and the date lives on the
-- entry -- so the join is always lines → entries and this is the side that needs
-- the index.
create index journal_lines_account_idx on public.journal_lines(account_id);

-- ── the two rules that cannot be bypassed ──────────────────────────────────

create or replace function public.assert_journal_balances()
returns trigger
language plpgsql set search_path = public as $$
declare
  v_entry uuid := coalesce(new.entry_id, old.entry_id);
  v_sum bigint;
  v_lines integer;
begin
  select coalesce(sum(amount_cents), 0), count(*) into v_sum, v_lines
    from public.journal_lines where entry_id = v_entry;

  -- Zero lines is the legitimate end state of deleting a draft's lines, and of
  -- the cascade when an entry is removed. Only a non-empty entry must balance.
  if v_lines = 0 then return null; end if;

  if v_lines < 2 then
    raise exception 'A journal entry needs at least two lines; this one has %.', v_lines
      using errcode = 'P0001';
  end if;

  if v_sum <> 0 then
    raise exception 'This entry does not balance: debits and credits differ by %.', v_sum
      using errcode = 'P0001';
  end if;

  return null;
end;
$$;

create constraint trigger journal_entry_balances
  after insert or update or delete on public.journal_lines
  deferrable initially deferred
  for each row execute function public.assert_journal_balances();

create or replace function public.refuse_posted_entry_edit()
returns trigger
language plpgsql set search_path = public as $$
begin
  -- The one legal transition on a posted row: reverse_journal_entry marking it
  -- reversed and pointing it at its mirror. Everything else about the row must
  -- be identical, which is what the row comparison below checks -- listing
  -- columns by name would silently stop covering any column added later.
  --
  -- IS NOT DISTINCT FROM, never =. A row comparison containing a null on both
  -- sides evaluates to NULL rather than true, so `=` here refused every
  -- reversal of an entry with no location_id -- which is every entry a
  -- single-store shop writes. The reversal failed with "A posted entry is
  -- immutable", accusing the one function allowed to make this change.
  if old.status = 'posted' and new.status = 'reversed'
     and new.reverses_entry_id is not null
     and (new.id, new.shop_id, new.period_id, new.entry_date, new.reference,
          new.description, new.source, new.location_id, new.created_by, new.created_at)
       is not distinct from
         (old.id, old.shop_id, old.period_id, old.entry_date, old.reference,
          old.description, old.source, old.location_id, old.created_by, old.created_at) then
    return new;
  end if;

  if old.status = 'posted' then
    raise exception 'A posted entry is immutable. Reverse it instead of editing it.'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

create trigger journal_entries_immutable
  before update on public.journal_entries
  for each row execute function public.refuse_posted_entry_edit();

create or replace function public.refuse_posted_line_change()
returns trigger
language plpgsql set search_path = public as $$
declare
  v_status text;
begin
  select status into v_status from public.journal_entries
    where id = coalesce(new.entry_id, old.entry_id);
  -- Null when the parent entry is already gone: this is the ON DELETE CASCADE
  -- tearing down a draft, not somebody editing a posted one.
  if v_status is not null and v_status <> 'draft' then
    raise exception 'The lines of a posted entry are immutable. Reverse the entry instead.'
      using errcode = 'P0001';
  end if;
  return coalesce(new, old);
end;
$$;

create trigger journal_lines_immutable
  before update or delete on public.journal_lines
  for each row execute function public.refuse_posted_line_change();

-- ── RLS ────────────────────────────────────────────────────────────────────
alter table public.journal_entries enable row level security;
alter table public.journal_lines enable row level security;

create policy "read journal_entries" on public.journal_entries for select
  using (has_shop_permission(shop_id, 'ledger.view'));
create policy "read journal_lines" on public.journal_lines for select
  using (exists (select 1 from public.journal_entries e
                  where e.id = entry_id and has_shop_permission(e.shop_id, 'ledger.view')));

-- No insert/update/delete policy, on purpose and for the same reason
-- stock_receipts, stock_transfers and stock_counts have none: an entry is only
-- ever written through post_journal_entry(), which resolves the period, checks
-- the balance, allocates the reference and writes the audit row in one
-- transaction. A direct insert would be an entry with no reference, possibly
-- in a closed month, that nothing recorded.
grant select on public.journal_entries, public.journal_lines to authenticated;
