-- Vendor bills (accounts payable): what the shop owes suppliers and is due to
-- pay later. Not customer invoicing -- money owed *to* the shop is a separate
-- future concern (see the marketplace work), deliberately not modelled here.
--
-- The central decision: **a bill is an unpaid expense.** Recording one posts a
-- linked row into `expenses` immediately, so the cost lands in the P&L when it
-- is *incurred*, not when it is paid. Payments against it are then pure cash
-- movements that never touch the P&L again.
--
-- Without this, an unpaid $400 rent bill would be invisible to Net profit
-- until settled, which both understates costs and contradicts how wages are
-- already accrued. Routing every cost through `expenses` also means reporting
-- has exactly one source of truth, so a bill and its expense cannot drift or
-- be double-counted.

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops(id) on delete cascade,
  -- Set null, not cascade: losing a vendor record must not erase the bills
  -- owed to them. The frozen name/phone below keep the row readable after.
  vendor_id uuid references public.vendors(id) on delete set null,
  vendor_name text,
  vendor_phone text,
  -- The supplier's own reference, typed in by the shop -- not a sequence we
  -- generate, since it has to match the paper the vendor sent.
  invoice_number text not null,
  category text not null check (category in (
    'inventory_purchase','rent','utilities','salaries_wages','marketing',
    'supplies','transport_delivery','maintenance_repairs','fees_charges',
    'owner_draw','other'
  )),
  description text,
  issued_on date not null default current_date,
  due_on date not null,
  amount_cents integer not null check (amount_cents > 0),
  -- Maintained solely by record_invoice_payment; never written directly.
  paid_cents integer not null default 0 check (paid_cents >= 0),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  constraint invoices_not_overpaid check (paid_cents <= amount_cents),
  unique (shop_id, invoice_number)
);
create index invoices_shop_id_idx on public.invoices(shop_id);
create index invoices_vendor_id_idx on public.invoices(vendor_id);
create index invoices_shop_due_idx on public.invoices(shop_id, due_on);

create table public.invoice_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  amount_cents integer not null check (amount_cents > 0),
  paid_on date not null default current_date,
  method text not null default 'cash' check (method in ('cash','zaad','edahab','other')),
  note text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create index invoice_payments_invoice_id_idx on public.invoice_payments(invoice_id);

-- The link back to the bill that generated an expense row. Cascade, so
-- deleting a bill takes its expense with it and the P&L stays consistent.
alter table public.expenses add column if not exists invoice_id uuid references public.invoices(id) on delete cascade;
create index expenses_invoice_id_idx on public.expenses(invoice_id);

comment on column public.expenses.invoice_id is
  'Set when this expense was generated by a vendor bill. Such rows are maintained by the invoice sync trigger and cannot be edited or deleted directly -- change the bill instead.';

alter table public.invoices enable row level security;
alter table public.invoice_payments enable row level security;

-- Same sales.view-inclusive read as expenses: anyone who can open Accounting
-- should see a coherent picture rather than revenue with costs missing.
create policy "read invoices" on public.invoices for select
  using (has_any_shop_permission(shop_id, array['invoices.view', 'invoices.manage', 'sales.view']));
create policy "insert invoices" on public.invoices for insert
  with check (has_shop_permission(shop_id, 'invoices.manage'));
create policy "update invoices" on public.invoices for update
  using (has_shop_permission(shop_id, 'invoices.manage'))
  with check (has_shop_permission(shop_id, 'invoices.manage'));
create policy "delete invoices" on public.invoices for delete
  using (has_shop_permission(shop_id, 'invoices.manage'));

create policy "read invoice_payments" on public.invoice_payments for select
  using (exists (
    select 1 from public.invoices i
    where i.id = invoice_id
      and has_any_shop_permission(i.shop_id, array['invoices.view', 'invoices.manage', 'sales.view'])
  ));
-- Writes go through record_invoice_payment, which keeps paid_cents in step;
-- this policy exists so the RPC's inserts are permitted and so a payment can
-- be corrected by deleting it, not so clients hand-roll their own.
create policy "write invoice_payments" on public.invoice_payments for all
  using (exists (select 1 from public.invoices i where i.id = invoice_id and has_shop_permission(i.shop_id, 'invoices.manage')))
  with check (exists (select 1 from public.invoices i where i.id = invoice_id and has_shop_permission(i.shop_id, 'invoices.manage')));

grant select, insert, update, delete on public.invoices to authenticated;
grant select, insert, update, delete on public.invoice_payments to authenticated;

-- Keeps each bill's expense row in step with the bill itself.
--
-- A trigger rather than doing this inside a "create invoice" RPC: the bill is
-- writable through ordinary RLS, so any direct UPDATE would otherwise leave
-- the expense stale. A trigger cannot be bypassed by whoever writes the row.
-- security definer because the expense policies below deliberately refuse
-- direct writes to invoice-linked rows -- including, without this, our own.
create or replace function public.sync_invoice_expense() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    insert into public.expenses (shop_id, occurred_on, amount_cents, category, vendor_id, payment_method, note, created_by, invoice_id)
      values (
        new.shop_id,
        -- The issue date, not today: a bill dated last month is last month's
        -- cost however late it gets entered.
        new.issued_on,
        new.amount_cents,
        new.category,
        new.vendor_id,
        'other',
        coalesce(nullif(new.description, ''), 'Bill ' || new.invoice_number),
        new.created_by,
        new.id
      );
    return new;
  end if;

  update public.expenses set
    occurred_on = new.issued_on,
    amount_cents = new.amount_cents,
    category = new.category,
    vendor_id = new.vendor_id,
    note = coalesce(nullif(new.description, ''), 'Bill ' || new.invoice_number),
    updated_at = now()
  where invoice_id = new.id;
  return new;
end;
$$;

create trigger invoices_sync_expense
  after insert or update of amount_cents, category, issued_on, description, vendor_id, invoice_number
  on public.invoices
  for each row execute function public.sync_invoice_expense();

-- Invoice- and payroll-generated expense rows are read-only from the Expenses
-- screen: the bill (or pay run) is the record of truth, and letting the
-- generated row be edited independently is exactly how a total and its source
-- drift apart. Corrections go through the bill.
--
-- Policies are dropped and recreated in full rather than altered, matching how
-- 0024 handles policy changes.
drop policy "update expenses" on public.expenses;
create policy "update expenses" on public.expenses for update
  using (has_shop_permission(shop_id, 'expenses.manage') and invoice_id is null)
  with check (has_shop_permission(shop_id, 'expenses.manage') and invoice_id is null);

drop policy "delete expenses" on public.expenses;
create policy "delete expenses" on public.expenses for delete
  using (has_shop_permission(shop_id, 'expenses.manage') and invoice_id is null);

-- Records a payment against a bill and advances paid_cents atomically.
--
-- Row-locks first, then validates against the *current* balance, so two
-- concurrent payments can't both pass a stale check and overpay the bill --
-- the same shape as refund_sale_items in the refunds migration.
--
-- Deliberately does not touch the expense row: the cost was recognised when
-- the bill was raised. A payment only settles what is owed.
create or replace function public.record_invoice_payment(
  p_invoice_id uuid,
  p_amount_cents integer,
  p_paid_on date default current_date,
  p_method text default 'cash',
  p_note text default null
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_invoice public.invoices%rowtype;
  v_payment_id uuid;
begin
  select * into v_invoice from public.invoices where id = p_invoice_id for update;
  if v_invoice.id is null then
    raise exception 'bill % not found', p_invoice_id;
  end if;
  if not public.has_shop_permission(v_invoice.shop_id, 'invoices.manage') then
    raise exception 'not authorized for bill %', p_invoice_id;
  end if;
  if p_amount_cents is null or p_amount_cents <= 0 then
    raise exception 'payment amount must be greater than zero';
  end if;
  if p_method not in ('cash','zaad','edahab','other') then
    raise exception 'invalid payment method %', p_method;
  end if;
  if v_invoice.paid_cents + p_amount_cents > v_invoice.amount_cents then
    raise exception 'payment of % exceeds the % still outstanding',
      p_amount_cents, v_invoice.amount_cents - v_invoice.paid_cents;
  end if;

  insert into public.invoice_payments (invoice_id, amount_cents, paid_on, method, note, created_by)
    values (p_invoice_id, p_amount_cents, p_paid_on, p_method, nullif(p_note, ''), auth.uid())
    returning id into v_payment_id;

  update public.invoices
    set paid_cents = paid_cents + p_amount_cents, updated_at = now(), updated_by = auth.uid()
    where id = p_invoice_id;

  return v_payment_id;
end;
$$;

grant execute on function public.record_invoice_payment(uuid, integer, date, text, text) to authenticated;

-- Manager is "everything except settings and staff management" (0020/0024).
-- Guarded so re-running is a no-op and a customised role isn't overwritten.
update public.roles
  set permissions = permissions || array['invoices.view', 'invoices.manage']
  where name = 'Manager'
    and permissions @> array['sales.edit', 'dashboard.view']
    and not permissions && array['invoices.manage'];
